### ISSUE TITLE
Monsters stop attacking and ....

### ISSUE THREAD

**Issue by anemul** [Stealth2800/The-Building-Game#9]
Hey it is me again , but I think I have a real issue this time . I am running a 1.8 Spigot server , I have GriefPrevention , world edit , world guard , bPermissions , multiverse-core and multiverse-portals . 
The issue is Monsters stop attacking and moving , some animals were acting weird as well and Villagers were normal . Monsters still spawn , they still make noises when your close to them though . Killing them still gives you experience and drops . I did not want to think it was BuildingGame causing this , especially after working so hard to get it working ( kinda ) players still could not use the signs . 
I removed plugins one at a time and restarted server , to no avail . Then I removed BuildingGames and the Monsters went back to normal . I then added each plugin back in one at a time restarting each time . I re-added Building Games last and the Monsters stopped moving and attacking again . I'm not sure what to do now . 

edit: BuildingGame is on its own world and I have a creative world and a survival world . I did get a long list off errors when it was just BuildingGame on the server . I will try to get that uploaded . 
sorry it wouldn't upload the .txt file for some reason .

[11:15:41 INFO]: [BuildingGame] Loading files
[11:15:42 INFO]: [BuildingGame] Loading arenas
[11:15:42 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:42 INFO]: [BuildingGame] Loading files
[11:15:43 INFO]: [BuildingGame] Loading arenas
[11:15:43 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:44 INFO]: [BuildingGame] Loading files
[11:15:44 INFO]: [BuildingGame] Loading arenas
[11:15:44 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:45 INFO]: [BuildingGame] Loading files
[11:15:45 INFO]: [BuildingGame] Loading arenas
[11:15:45 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:46 INFO]: [BuildingGame] Loading files
[11:15:46 INFO]: [BuildingGame] Loading arenas
[11:15:46 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:47 INFO]: [BuildingGame] Loading files
[11:15:47 INFO]: [BuildingGame] Loading arenas
[11:15:47 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:48 INFO]: [BuildingGame] Loading files
[11:15:48 INFO]: [BuildingGame] Loading arenas
[11:15:48 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:49 INFO]: [BuildingGame] Loading files
[11:15:49 INFO]: [BuildingGame] Loading arenas
[11:15:49 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
[11:15:50 INFO]: [BuildingGame] Loading files
[11:15:50 INFO]: [BuildingGame] Loading arenas
[11:15:50 WARN]: [BuildingGame] Task #2 for BuildingGame v1.11.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at me.stefvanschie.buildinggame.managers.arenas.SignManager.setup(SignManager.java:35) ~[?:?]
    at me.stefvanschie.buildinggame.Main.loadPlugin(Main.java:133) ~[?:?]
    at me.stefvanschie.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:18) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

> stop
> [11:15:50 INFO]: Stopping the server
> [11:15:50 INFO]: Stopping server
> [11:15:50 INFO]: [BuildingGame] Disabling BuildingGame v1.11.0
> [11:15:50 INFO]: [BuildingGame] BuildingGame has been disabled
> [11:15:50 INFO]: Saving players
> [11:15:50 INFO]: Saving worlds
> [11:15:50 INFO]: Saving chunks for level 'funhouse'/Overworld
> [11:15:51 INFO]: Saving chunks for level 'funhouse_the_end'/The End

**Comment by Stealth2800** [comment]
Not my plugin. https://github.com/stefvanschie/buildinggame

**Comment by anemul** [comment]
Actually it is , the problem stops when I take your game out , and starts backup no matter if I have nothing but MV and MVP in there .

**Comment by anemul** [comment]
This the first clue I have came across and the problem stops when I take
your plugin out , can you at least offer me a direction to look ? Help me
get it going ? I like and want to use your plugin .
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Stealth2800** [comment]
`me.stefvanschie.buildinggame.managers.arenas.SignManager`

That's not my package name.  Also, my plugin is called "TheBuildingGame", not "BuildingGame"
